name: deploy-workflow
on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    steps:
      - yarn lint
  build:
    steps:
      - yarn build
      - yarn export
  deploy:
    steps:
      - touch out/.nojekyll 
      - git add -f out 
      - git commit -m '(workflow) deploy' 
      - git subtree push --prefix out origin gh-pages 
  clean:
    steps:
      - rm -r out/ 
      - git add -f out/ 
      - git commit -m '(workflow) clean'



